/**
 * Las vistas por requisito que pide la cátedra. Cada ficha declara solo lo que
 * le aplica: la autenticación no lleva componentes porque no aporta nada verlos,
 * y el catálogo sí, porque la pregunta «qué componente muestra el catálogo» es
 * justamente la que hay que contestar.
 *
 * Los pasos de cada secuencia son los del sistema real, no una idealización:
 * se corresponden con las postcondiciones declaradas en el apartado 3.2.
 */

import { ficha } from './fichas-uml.mjs'

const FICHAS = [
  {
    id: 'RF01',
    nombre: 'Autenticación del administrador',
    resumen:
      'Quién entra al panel y qué comprueba el sistema antes de dejarlo pasar. No lleva vista de componentes: la función no se explica mejor con ellos.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Iniciar sesión en el panel'],
    participantes: ['Operador', 'Pantalla de acceso', 'Servidor', 'Autenticación', 'admin_users'],
    mensajes: [
      { de: 0, a: 1, texto: 'escribe usuario y contraseña' },
      { de: 1, a: 2, texto: 'signIn(usuario, contraseña)' },
      { de: 2, a: 2, texto: 'traduce el usuario a su correo interno' },
      { de: 2, a: 3, texto: 'verifica la contraseña' },
      { de: 3, a: 2, texto: 'sesión válida y rol del metadato', tipo: 'respuesta' },
      { de: 2, a: 4, texto: '¿pertenece al panel y sigue vigente?' },
      { de: 4, a: 2, texto: 'fila con revoked_at', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'entra, o el motivo del rechazo', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'La contraseña nunca llega al servidor de la tienda: viaja al servicio de autenticación y vuelve una sesión. Un acceso retirado se rechaza acá aunque la contraseña siga siendo correcta.',
  },
  {
    id: 'RF02',
    nombre: 'Consulta y filtrado del catálogo',
    resumen:
      'Quién ve el catálogo, cómo se comporta el sistema cuando lo filtran y de qué partes se sirve.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Consultar el catálogo', 'Filtrar por marca y precio'],
    participantes: ['Cliente', 'Vitrina', 'Servidor', 'products'],
    mensajes: [
      { de: 0, a: 1, texto: 'abre el catálogo' },
      { de: 1, a: 2, texto: 'pide la página' },
      { de: 2, a: 3, texto: 'lee las piezas activas' },
      { de: 3, a: 2, texto: 'fichas, precios y existencias', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'página ya generada', tipo: 'respuesta' },
      { de: 0, a: 1, texto: 'aplica filtros' },
      { de: 1, a: 1, texto: 'filtra en el navegador y escribe la URL' },
      { de: 1, a: 0, texto: 'resultados, sin recargar la página', tipo: 'respuesta' },
    ],
    componentes: ['Catálogo', 'Filtros y búsqueda', 'Conversión de moneda'],
    nota: 'Las páginas del catálogo se generan de antemano, así que la primera consulta no espera a la base. El filtrado ocurre en el navegador y queda escrito en la dirección, de modo que un filtro se puede compartir por enlace.',
  },
  {
    id: 'RF06',
    nombre: 'Gestión del carrito de compras',
    resumen: 'Quién arma el carrito y qué hace el sistema para que sobreviva a cerrar el navegador.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Agregar una pieza', 'Cambiar cantidades', 'Quitar una línea'],
    participantes: ['Cliente', 'Ficha de producto', 'Carrito', 'Almacenamiento local'],
    mensajes: [
      { de: 0, a: 1, texto: 'elige variante y cantidad' },
      { de: 1, a: 2, texto: 'agrega la línea' },
      { de: 2, a: 2, texto: 'suma el subtotal en dólares' },
      { de: 2, a: 3, texto: 'guarda el estado' },
      { de: 2, a: 0, texto: 'contador y subtotal al día', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'El carrito vive únicamente en el navegador del cliente: el sistema no guarda carritos ajenos ni necesita que nadie se registre para tener uno.',
  },
  {
    id: 'RF10',
    nombre: 'Registro del pedido',
    resumen:
      'Quién registra el pedido y qué hace la base para que dos clientes no se lleven la misma unidad.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Registrar el pedido'],
    participantes: ['Cliente', 'Checkout', 'Base de datos', 'orders'],
    mensajes: [
      { de: 0, a: 1, texto: 'confirma sus datos de entrega' },
      { de: 1, a: 2, texto: 'place_order(líneas, cliente, destino, cupón)' },
      { de: 2, a: 2, texto: 'relee el precio vigente de cada pieza' },
      { de: 2, a: 2, texto: 'bloquea las filas y comprueba existencias' },
      { de: 2, a: 3, texto: 'graba el pedido y sus líneas' },
      { de: 3, a: 2, texto: 'número correlativo asignado', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'número de pedido, o la pieza que faltó', tipo: 'respuesta' },
    ],
    componentes: ['Checkout', 'Funciones transaccionales', 'Control de existencias'],
    nota: 'El cliente transmite identificadores y cantidades, nunca importes: los precios se releen del catálogo dentro de la transacción. Si una pieza no alcanza, no se graba nada.',
  },
  {
    id: 'RF11',
    nombre: 'Generación del mensaje y cierre por WhatsApp',
    resumen: 'Quién cierra la venta y por qué el sistema no envía el mensaje en nombre del cliente.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Generar el mensaje', 'Abrir la conversación'],
    participantes: ['Cliente', 'Checkout', 'Redactor', 'WhatsApp'],
    mensajes: [
      { de: 1, a: 2, texto: 'pide el texto del pedido' },
      { de: 2, a: 2, texto: 'convierte con la tasa grabada en el pedido' },
      { de: 2, a: 1, texto: 'mensaje y enlace oficial', tipo: 'respuesta' },
      { de: 1, a: 0, texto: 'botón listo para abrir la conversación', tipo: 'respuesta' },
      { de: 0, a: 3, texto: 'el propio cliente abre y envía' },
    ],
    componentes: ['Redactor de mensajes', 'Conversión de moneda'],
    nota: 'El sistema prepara el texto y el enlace; el envío lo hace la persona. Se usa la dirección oficial de WhatsApp y no el atajo wa.me, porque este último altera los emojis al redirigir.',
  },
  {
    id: 'RF17',
    nombre: 'Alta de cuentas de administración',
    resumen:
      'Quién puede crear cuentas del panel y qué comprueba el servidor antes de crear ninguna identidad.',
    actor: { nombre: 'Moderador', nota: 'titular · usuario «Cielo»', paleta: 'moderador' },
    casos: ['Crear una cuenta de administrador'],
    participantes: ['Moderador', 'Configuración', 'Servidor', 'Autenticación', 'admin_users'],
    mensajes: [
      { de: 0, a: 1, texto: 'usuario, nombre y contraseña' },
      { de: 1, a: 2, texto: 'createPanelAccount()' },
      { de: 2, a: 2, texto: 'exige rol de moderador antes de seguir' },
      { de: 2, a: 4, texto: '¿ese usuario ya existe?' },
      { de: 2, a: 3, texto: 'crea la identidad con rol administrador' },
      { de: 3, a: 2, texto: 'identidad creada', tipo: 'respuesta' },
      { de: 2, a: 4, texto: 'registra la pertenencia al panel' },
      { de: 2, a: 1, texto: 'alta confirmada', tipo: 'respuesta' },
    ],
    componentes: ['Gestión de cuentas', 'Autenticación', 'Guardia de sesión y rol'],
    nota: 'El formulario no decide el rol: toda cuenta creada desde el panel nace como administrador. Si la pertenencia no llega a registrarse, se elimina la identidad recién creada para no dejar una cuenta huérfana.',
  },
  {
    id: 'RF03',
    nombre: 'Búsqueda insensible a acentos y mayúsculas',
    resumen: 'Quién busca y qué hace el sistema para que «grafica» encuentre «gráfica».',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Buscar una pieza'],
    participantes: ['Cliente', 'Vitrina', 'Índice de búsqueda'],
    mensajes: [
      { de: 0, a: 1, texto: 'escribe «grafica rtx»' },
      { de: 1, a: 2, texto: 'consulta el término' },
      { de: 2, a: 2, texto: 'normaliza los dos lados: sin tildes ni mayúsculas' },
      { de: 2, a: 1, texto: 'piezas que coinciden', tipo: 'respuesta' },
      { de: 1, a: 0, texto: 'resultados, o una salida si no hay ninguno', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'Se normalizan ambos lados de la comparación, no solo lo escrito: nadie teclea las tildes al buscar, y el catálogo sí las lleva.',
  },
  {
    id: 'RF04',
    nombre: 'Selección dinámica de variantes',
    resumen: 'Quién elige una variante y cómo cambia la ficha sin volver a cargar la página.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Elegir una variante'],
    participantes: ['Cliente', 'Ficha de producto', 'product_variants'],
    mensajes: [
      { de: 0, a: 1, texto: 'abre la ficha de una pieza' },
      { de: 1, a: 2, texto: 'pide las variantes activas' },
      { de: 2, a: 1, texto: 'ejes, SKU, precio y existencias', tipo: 'respuesta' },
      { de: 1, a: 1, texto: 'deriva los ejes de las propias variantes' },
      { de: 0, a: 1, texto: 'elige capacidad, velocidad o formato' },
      { de: 1, a: 0, texto: 'foto, código, precio y stock de esa variante', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'Los ejes no están declarados de antemano: se deducen de las variantes que el producto tenga. En componentes de PC no hay talla ni color fijos.',
  },
  {
    id: 'RF05',
    nombre: 'Compra directa desde la ficha',
    resumen: 'Quién compra una sola pieza sin pasar por el carrito, y qué prepara el sistema.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Comprar una pieza directo'],
    participantes: ['Cliente', 'Ficha de producto', 'Redactor', 'WhatsApp'],
    mensajes: [
      { de: 0, a: 1, texto: 'pulsa «Comprar por WhatsApp»' },
      { de: 1, a: 2, texto: 'nombre, código, cantidad y precio' },
      { de: 2, a: 2, texto: 'convierte a guaraníes con la tasa vigente' },
      { de: 2, a: 1, texto: 'mensaje redactado y enlace', tipo: 'respuesta' },
      { de: 0, a: 3, texto: 'el propio cliente abre y envía' },
    ],
    componentes: ['Ficha de producto', 'Redactor de mensajes'],
    nota: 'Este camino no registra pedido: es una consulta por una pieza. El registro ocurre solo cuando se cierra un pedido completo desde el checkout.',
  },
  {
    id: 'RF07',
    nombre: 'Verificación de compatibilidad entre componentes',
    resumen: 'Quién arma un equipo y cómo el sistema le avisa qué no encaja.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Armar un equipo', 'Probar el encendido'],
    participantes: ['Cliente', 'Configurador', 'Reglas de compatibilidad'],
    mensajes: [
      { de: 0, a: 1, texto: 'elige procesador y placa madre' },
      { de: 1, a: 2, texto: 'compara zócalo, memoria, vatiaje y milímetros' },
      { de: 2, a: 1, texto: 'choques encontrados', tipo: 'respuesta' },
      { de: 1, a: 0, texto: 'aviso en castellano llano, no en jerga', tipo: 'respuesta' },
      { de: 0, a: 1, texto: 'pide la prueba de encendido' },
      { de: 1, a: 0, texto: 'si el armado enciende, o qué le falta', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'Solo lectura sobre los datos de compatibilidad del catálogo: verificar un armado no escribe nada en la base.',
  },
  {
    id: 'RF08',
    nombre: 'Conversión y presentación multimoneda',
    resumen: 'Quién ve el precio en su moneda y de dónde sale cada cifra.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Ver el precio en su moneda'],
    participantes: ['Cliente', 'Vitrina', 'Conversión', 'settings'],
    mensajes: [
      { de: 1, a: 3, texto: 'lee la tasa vigente' },
      { de: 3, a: 1, texto: 'guaraníes y reales por dólar', tipo: 'respuesta' },
      { de: 0, a: 1, texto: 'cambia de moneda' },
      { de: 1, a: 2, texto: 'convierte desde el dólar' },
      { de: 2, a: 2, texto: 'redondea de vitrina: al millar en guaraníes' },
      { de: 2, a: 0, texto: 'importe, sin recargar la página', tipo: 'respuesta' },
    ],
    componentes: ['Conversión de moneda', 'Configuración comercial'],
    nota: 'El dólar es la única fuente de verdad: no existe ningún precio escrito en guaraníes en los datos. Guaraní y real se derivan siempre de la tasa configurada.',
  },
  {
    id: 'RF09',
    nombre: 'Validación y aplicación de cupón de descuento',
    resumen: 'Quién aplica un cupón y por qué el listado de cupones nunca sale de la base.',
    actor: { nombre: 'Cliente', nota: 'sin cuenta ni registro', paleta: 'cliente' },
    casos: ['Aplicar un cupón'],
    participantes: ['Cliente', 'Checkout', 'validate_coupon', 'coupons'],
    mensajes: [
      { de: 0, a: 1, texto: 'escribe el código' },
      { de: 1, a: 2, texto: 'código y subtotal en dólares' },
      { de: 2, a: 3, texto: 'busca el código' },
      { de: 3, a: 2, texto: 'tipo, valor, vigencia y límite de usos', tipo: 'respuesta' },
      { de: 2, a: 2, texto: 'comprueba fechas, compra mínima y usos restantes' },
      { de: 2, a: 1, texto: 'descuento ya calculado, o el motivo del rechazo', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'La función devuelve el importe del descuento, nunca la lista de cupones. Así nadie puede enumerar los códigos vigentes probando desde el navegador.',
  },
  {
    id: 'RF12',
    nombre: 'Administración de productos y variantes',
    resumen: 'Quién mantiene el catálogo y qué comprueba la base antes de aceptar la escritura.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Dar de alta una pieza', 'Editarla', 'Darla de baja'],
    participantes: ['Administrador', 'Panel', 'Servidor', 'products'],
    mensajes: [
      { de: 0, a: 1, texto: 'completa la ficha de la pieza' },
      { de: 1, a: 2, texto: 'saveProduct()' },
      { de: 2, a: 2, texto: 'comprueba la sesión y el acceso vigente' },
      { de: 2, a: 3, texto: 'inserta o actualiza, sujeto a las políticas de fila' },
      { de: 3, a: 2, texto: 'fila grabada', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'confirmación y páginas públicas revalidadas', tipo: 'respuesta' },
    ],
    componentes: ['Acciones de servidor', 'Políticas de seguridad por fila'],
    nota: 'La comprobación de permiso ocurre dos veces: en el servidor y otra vez dentro de la base. Aunque alguien encontrara una ruta sin guardia, Postgres le niega la escritura.',
  },
  {
    id: 'RF13',
    nombre: 'Control de existencias con aviso de mínimo',
    resumen: 'Quién ajusta el stock y cómo se deriva la disponibilidad que ve el cliente.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Ajustar existencias'],
    participantes: ['Administrador', 'Listado de productos', 'Servidor', 'products'],
    mensajes: [
      { de: 0, a: 1, texto: 'escribe las unidades disponibles' },
      { de: 1, a: 2, texto: 'setStock(pieza, unidades)' },
      { de: 2, a: 3, texto: 'actualiza units' },
      { de: 3, a: 2, texto: 'valor grabado', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'aviso si quedó bajo el mínimo configurado', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'No existe ningún campo «agotado» que pueda contradecir al stock: la disponibilidad se deriva siempre de units, y por eso dar de baja un pedido tiene que devolver esas unidades.',
  },
  {
    id: 'RF14',
    nombre: 'Configuración de precios y tasa de cambio',
    resumen: 'Quién fija la tasa y qué impide que un error de tecleo reviente todos los precios.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Fijar la tasa de cambio', 'Fijar el umbral de aviso'],
    participantes: ['Administrador', 'Panel de precios', 'Servidor', 'settings'],
    mensajes: [
      { de: 0, a: 1, texto: 'escribe los guaraníes por dólar' },
      { de: 1, a: 1, texto: 'avisa en rojo mientras escribe si el valor es imposible' },
      { de: 1, a: 2, texto: 'saveFx()' },
      { de: 2, a: 2, texto: 'exige entre 1000 y 20000 guaraníes, y 1 a 50 reales' },
      { de: 2, a: 3, texto: 'graba la tasa y su marca temporal' },
      { de: 2, a: 1, texto: 'propagado a toda la tienda, sin desplegar de nuevo', tipo: 'respuesta' },
    ],
    componentes: ['Configuración comercial', 'Conversión de moneda'],
    nota: 'El rango no es un capricho: acá el guaraní se escribe «7.400» con punto de millar, y un campo numérico se lo come y guarda 7. Ese error dividió por mil todos los precios publicados una vez.',
  },
  {
    id: 'RF15',
    nombre: 'Administración de cupones de descuento',
    resumen: 'Quién crea los cupones y qué se valida antes de guardarlos.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Crear un cupón', 'Editarlo', 'Darlo de baja'],
    participantes: ['Administrador', 'Panel de cupones', 'Servidor', 'coupons'],
    mensajes: [
      { de: 0, a: 1, texto: 'código, tipo, valor y vigencia' },
      { de: 1, a: 2, texto: 'saveCoupon()' },
      { de: 2, a: 2, texto: 'un porcentaje no puede pasar de cien' },
      { de: 2, a: 3, texto: 'inserta o actualiza, con el código en mayúsculas' },
      { de: 3, a: 2, texto: 'cupón grabado', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'confirmación', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'El contador de usos lo lleva la base al aplicar el cupón en un pedido, no el panel: así dos compras simultáneas no pueden pasarse del límite.',
  },
  {
    id: 'RF16',
    nombre: 'Seguimiento interno de pedidos',
    resumen: 'Quién sigue los pedidos y por qué los importes que ve no se recalculan.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Consultar el historial', 'Cambiar el estado', 'Anotar una observación'],
    participantes: ['Administrador', 'Panel de pedidos', 'Servidor', 'orders'],
    mensajes: [
      { de: 0, a: 1, texto: 'abre el historial' },
      { de: 1, a: 2, texto: 'listOrders()' },
      { de: 2, a: 3, texto: 'lee pedidos y líneas, sujeto a las políticas de fila' },
      { de: 3, a: 2, texto: 'importes y tasa tal como se grabaron', tipo: 'respuesta' },
      { de: 0, a: 1, texto: 'cambia el estado o anota algo interno' },
      { de: 1, a: 2, texto: 'setOrderStatus() · setOrderNote()' },
      { de: 2, a: 3, texto: 'actualiza estado y nota' },
    ],
    componentes: null,
    nota: 'Los importes mostrados son los grabados con el pedido, no los del catálogo de hoy: un pedido de hace un mes tiene que seguir diciendo lo que se le prometió al cliente.',
  },
  {
    id: 'RF18',
    nombre: 'Retiro y restitución del acceso',
    resumen: 'Quién puede cortar el acceso de otro y por qué el corte llega hasta la base.',
    actor: { nombre: 'Moderador', nota: 'titular · usuario «Cielo»', paleta: 'moderador' },
    casos: ['Retirar el acceso', 'Devolver el acceso'],
    participantes: ['Moderador', 'Configuración', 'Servidor', 'admin_users'],
    mensajes: [
      { de: 0, a: 1, texto: 'elige la cuenta y confirma' },
      { de: 1, a: 2, texto: 'setPanelAccess(cuenta, intención)' },
      { de: 2, a: 2, texto: 'exige moderador; prohíbe la cuenta propia y otro moderador' },
      { de: 2, a: 3, texto: 'escribe o borra revoked_at' },
      { de: 3, a: 2, texto: 'estado actualizado', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'acceso retirado, o devuelto', tipo: 'respuesta' },
    ],
    componentes: ['Gestión de cuentas', 'Políticas de seguridad por fila'],
    nota: 'La cuenta no se borra: conserva su identidad y su contraseña. Lo que caduca es el permiso, y la función is_admin() deja de reconocerla, de modo que el token que ya tenga en el navegador tampoco le sirve.',
  },
  {
    id: 'RF19',
    nombre: 'Cambio de la contraseña propia',
    resumen: 'Quién cambia su clave y cómo se comprueba la actual sin cortarle la sesión.',
    actor: { nombre: 'Administrador', nota: 'y también el moderador', paleta: 'admin' },
    casos: ['Cambiar mi contraseña'],
    participantes: ['Operador', 'Configuración', 'Servidor', 'Autenticación'],
    mensajes: [
      { de: 0, a: 1, texto: 'actual, nueva y repetición' },
      { de: 1, a: 2, texto: 'changeOwnPassword()' },
      { de: 2, a: 3, texto: 'comprueba la actual en una sesión aislada, sin cookies' },
      { de: 3, a: 2, texto: 'misma identidad confirmada', tipo: 'respuesta' },
      { de: 2, a: 3, texto: 'actualiza la credencial' },
      { de: 2, a: 2, texto: 'cierra la sesión auxiliar de comprobación' },
      { de: 2, a: 1, texto: 'contraseña actualizada', tipo: 'respuesta' },
    ],
    componentes: null,
    nota: 'La comprobación usa un cliente aparte y sin cookies a propósito: verificar la contraseña vigente no debe reemplazar ni invalidar la sesión que el operador tiene abierta.',
  },
  {
    id: 'RF20',
    nombre: 'Baja de pedidos con restitución de existencias',
    resumen: 'Quién da de baja un pedido y por qué las unidades tienen que volver al inventario.',
    actor: { nombre: 'Moderador', nota: 'titular · usuario «Cielo»', paleta: 'moderador' },
    casos: ['Dar de baja un pedido'],
    participantes: ['Moderador', 'Panel de pedidos', 'delete_order', 'products'],
    mensajes: [
      { de: 0, a: 1, texto: 'transcribe el número del pedido' },
      { de: 1, a: 2, texto: 'delete_order(pedido)' },
      { de: 2, a: 2, texto: 'exige rol de moderador' },
      { de: 2, a: 2, texto: 'bloquea la fila del pedido' },
      { de: 2, a: 3, texto: 'devuelve las unidades, salvo si ya se entregó' },
      { de: 2, a: 2, texto: 'borra el pedido; las líneas caen en cascada' },
      { de: 2, a: 1, texto: 'número borrado y unidades devueltas', tipo: 'respuesta' },
    ],
    componentes: ['Funciones transaccionales', 'Control de existencias'],
    nota: 'Devolver el stock y borrar la fila ocurren en la misma transacción. En dos pasos, un fallo del segundo dejaría las unidades devueltas y el pedido en pie, y reintentarlo las devolvería otra vez.',
  },
  {
    id: 'RF21',
    nombre: 'Restablecimiento de la contraseña de otra cuenta',
    resumen: 'Quién puede darle una clave nueva a otro, y sobre qué cuentas no puede hacerlo.',
    actor: { nombre: 'Moderador', nota: 'titular · usuario «Cielo»', paleta: 'moderador' },
    casos: ['Restablecer la clave de un administrador'],
    participantes: ['Moderador', 'Configuración', 'Servidor', 'Autenticación'],
    mensajes: [
      { de: 0, a: 1, texto: 'elige la cuenta y escribe la clave nueva' },
      { de: 1, a: 2, texto: 'resetPanelPassword()' },
      { de: 2, a: 2, texto: 'exige moderador; rechaza la propia y la de otro moderador' },
      { de: 2, a: 3, texto: 'asigna la nueva credencial' },
      { de: 3, a: 2, texto: 'credencial cambiada', tipo: 'respuesta' },
      { de: 2, a: 1, texto: 'la clave anterior deja de servir', tipo: 'respuesta' },
    ],
    componentes: ['Gestión de cuentas', 'Autenticación'],
    nota: 'No se exige la contraseña vigente, porque el moderador no la conoce ni debe conocerla. Por eso mismo la operación queda acotada a cuentas de perfil administrador: nadie se apodera de una cuenta de igual jerarquía.',
  },
]

for (const f of FICHAS) console.log('  ' + ficha(f))
console.log(`\n${FICHAS.length} fichas generadas en docs/srs/`)
