import type { L10n } from '@/lib/i18n/locales'
import type { Product } from './types'

/**
 * CATÁLOGO
 *
 * Reglas que este archivo respeta y que conviene no romper al editarlo:
 *
 * 1. Los modelos son comerciales reales y sus especificaciones fueron verificadas
 *    contra la ficha del fabricante. Si un dato no se pudo verificar, no se escribe.
 * 2. Precio, unidades y condiciones son datos de configuración de esta tienda, no
 *    información oficial del fabricante. La interfaz lo dice donde corresponde.
 * 3. `units` es la única fuente de la disponibilidad. No existe ningún campo
 *    «agotado» que pueda contradecirla, y la oferta se deriva de `listPriceUsd`.
 * 4. `compat` es el dato que consume el configurador. Cambiar un número acá cambia
 *    las advertencias de compatibilidad, no hay una segunda copia en otro lado.
 */

const L = (es: string, pt: string): L10n => ({ es, pt })

// Paleta de materiales para los renders. Metales y cobre: son materiales reales
// de la pieza, no colores semánticos de la interfaz.
const STEEL = '#6E7A85'
const GRAPHITE = '#414D58'
const NICKEL = '#98A3AD'
const COPPER = '#B87A4E'
const SKY = '#55C8F5'

const S = {
  memory: L('Memoria', 'Memória'),
  bus: L('Interfaz', 'Interface'),
  busWidth: L('Bus de memoria', 'Barramento'),
  tgp: L('Consumo de la placa', 'Consumo da placa'),
  psu: L('Fuente recomendada', 'Fonte recomendada'),
  power: L('Conector de poder', 'Conector de energia'),
  length: L('Longitud', 'Comprimento'),
  slots: L('Ranuras que ocupa', 'Slots ocupados'),
  socket: L('Zócalo', 'Soquete'),
  cores: L('Núcleos e hilos', 'Núcleos e threads'),
  tdp: L('Potencia base', 'Potência base'),
  igpu: L('Video integrado', 'Vídeo integrado'),
  chipset: L('Chipset', 'Chipset'),
  format: L('Formato', 'Formato'),
  ramSlots: L('Ranuras de memoria', 'Slots de memória'),
  ramGen: L('Generación', 'Geração'),
  kit: L('Kit', 'Kit'),
  speed: L('Velocidad', 'Velocidade'),
  latency: L('Latencia', 'Latência'),
  capacity: L('Capacidad', 'Capacidade'),
  read: L('Lectura secuencial', 'Leitura sequencial'),
  write: L('Escritura secuencial', 'Escrita sequencial'),
  watts: L('Potencia', 'Potência'),
  efficiency: L('Certificación', 'Certificação'),
  modular: L('Cableado', 'Cabeamento'),
  coolType: L('Tipo', 'Tipo'),
  height: L('Altura', 'Altura'),
  radiator: L('Radiador', 'Radiador'),
  sockets: L('Zócalos soportados', 'Soquetes suportados'),
  supports: L('Placas que admite', 'Placas suportadas'),
  maxGpu: L('Placa de video máx.', 'Placa de vídeo máx.'),
  maxCooler: L('Disipador máx.', 'Cooler máx.'),
  maxRad: L('Radiador máx.', 'Radiador máx.'),
  contents: L('Contenido', 'Conteúdo'),
  size: L('Tamaño', 'Tamanho'),
}

export const PRODUCTS: Product[] = [
  // ─────────────────────────────────────────────────────── tarjetas gráficas
  {
    slug: 'geforce-rtx-5080-16gb',
    ref: 'SI-VGA-0112',
    name: 'GeForce RTX 5080 16 GB',
    brand: 'NVIDIA',
    model: 'RTX 5080',
    category: 'tarjetas-graficas',
    priceUsd: 1724,
    units: 2,
    featured: true,
    arrivedRecently: true,
    blurb: L(
      'El escalón donde 4K deja de ser una concesión. 16 GB de GDDR7 sobre bus de 256 bits y arquitectura Blackwell; pide una fuente de 850 W y un gabinete que acepte 336 mm.',
      'O degrau em que 4K deixa de ser concessão. 16 GB de GDDR7 em barramento de 256 bits e arquitetura Blackwell; pede fonte de 850 W e um gabinete que aceite 336 mm.',
    ),
    specs: [
      { label: S.memory, value: '16 GB GDDR7' },
      { label: S.busWidth, value: '256 bit' },
      { label: L('Núcleos CUDA', 'Núcleos CUDA'), value: '10.752' },
      { label: S.bus, value: 'PCIe 5.0 ×16' },
      { label: S.tgp, value: '360 W' },
      { label: S.psu, value: '850 W' },
      { label: S.power, value: '1× 12V-2×6 (450 W+)' },
      { label: S.length, value: '336 mm' },
      { label: S.slots, value: '3' },
    ],
    compat: {
      kind: 'gpu',
      lengthMm: 336,
      slots: 3,
      tgpW: 360,
      recommendedPsuW: 850,
      power: '1× 12V-2×6',
      bus: 'PCIe 5.0 ×16',
      vramGb: 16,
      vramType: 'GDDR7',
      busWidthBit: 256,
    },
    render: { shape: 'gpu', accent: GRAPHITE, seed: 12, fans: 3, variant: 0 },
  },
  {
    slug: 'geforce-rtx-5070-ti-16gb',
    ref: 'SI-VGA-0118',
    name: 'GeForce RTX 5070 Ti 16 GB',
    brand: 'NVIDIA',
    model: 'RTX 5070 Ti',
    category: 'tarjetas-graficas',
    priceUsd: 1249,
    listPriceUsd: 1367,
    units: 5,
    featured: true,
    blurb: L(
      'Los mismos 16 GB de GDDR7 que el escalón de arriba, con 300 W en lugar de 360. La opción sensata para 1440p alto y 4K con reconstrucción.',
      'Os mesmos 16 GB de GDDR7 do degrau acima, com 300 W em vez de 360. A escolha sensata para 1440p alto e 4K com reconstrução.',
    ),
    specs: [
      { label: S.memory, value: '16 GB GDDR7' },
      { label: S.busWidth, value: '256 bit' },
      { label: L('Núcleos CUDA', 'Núcleos CUDA'), value: '8.960' },
      { label: S.bus, value: 'PCIe 5.0 ×16' },
      { label: S.tgp, value: '300 W' },
      { label: S.psu, value: '750 W' },
      { label: S.power, value: '1× 12V-2×6 (300 W+)' },
      { label: S.length, value: '304 mm' },
      { label: S.slots, value: '2' },
    ],
    compat: {
      kind: 'gpu',
      lengthMm: 304,
      slots: 2,
      tgpW: 300,
      recommendedPsuW: 750,
      power: '1× 12V-2×6',
      bus: 'PCIe 5.0 ×16',
      vramGb: 16,
      vramType: 'GDDR7',
      busWidthBit: 256,
    },
    render: { shape: 'gpu', accent: STEEL, seed: 31, fans: 3, variant: 1 },
  },
  {
    slug: 'geforce-rtx-5070-12gb',
    ref: 'SI-VGA-0124',
    name: 'GeForce RTX 5070 12 GB',
    brand: 'NVIDIA',
    model: 'RTX 5070',
    category: 'tarjetas-graficas',
    priceUsd: 819,
    units: 7,
    blurb: L(
      'GDDR7 en 192 bits y 250 W: entra en una fuente de 650 W y en casi cualquier gabinete de torre media. El punto donde 1440p deja de exigir concesiones.',
      'GDDR7 em 192 bits e 250 W: cabe numa fonte de 650 W e em quase qualquer gabinete médio. O ponto em que 1440p para de exigir concessões.',
    ),
    specs: [
      { label: S.memory, value: '12 GB GDDR7' },
      { label: S.busWidth, value: '192 bit' },
      { label: L('Núcleos CUDA', 'Núcleos CUDA'), value: '6.144' },
      { label: S.bus, value: 'PCIe 5.0 ×16' },
      { label: S.tgp, value: '250 W' },
      { label: S.psu, value: '650 W' },
      { label: S.power, value: '1× 12V-2×6 (300 W)' },
      { label: S.length, value: '242 mm' },
      { label: S.slots, value: '2' },
    ],
    compat: {
      kind: 'gpu',
      lengthMm: 242,
      slots: 2,
      tgpW: 250,
      recommendedPsuW: 650,
      power: '1× 12V-2×6',
      bus: 'PCIe 5.0 ×16',
      vramGb: 12,
      vramType: 'GDDR7',
      busWidthBit: 192,
    },
    render: { shape: 'gpu', accent: STEEL, seed: 44, fans: 2, variant: 0 },
  },
  {
    slug: 'radeon-rx-9070-xt-16gb',
    ref: 'SI-VGA-0131',
    name: 'Radeon RX 9070 XT 16 GB',
    brand: 'AMD',
    model: 'RX 9070 XT',
    category: 'tarjetas-graficas',
    priceUsd: 799,
    units: 4,
    featured: true,
    blurb: L(
      '16 GB de GDDR6 sobre 256 bits en arquitectura RDNA 4. Consume 304 W y AMD recomienda 750 W de fuente; es la alternativa directa al escalón de 16 GB del otro fabricante.',
      '16 GB de GDDR6 em 256 bits com arquitetura RDNA 4. Consome 304 W e a AMD recomenda fonte de 750 W; é a alternativa direta ao degrau de 16 GB do outro fabricante.',
    ),
    specs: [
      { label: S.memory, value: '16 GB GDDR6' },
      { label: S.busWidth, value: '256 bit' },
      { label: S.bus, value: 'PCIe 5.0 ×16' },
      { label: S.tgp, value: '304 W' },
      { label: S.psu, value: '750 W' },
      { label: S.power, value: '2× PCIe 8 pines' },
      { label: S.length, value: '320 mm' },
      { label: S.slots, value: '3' },
    ],
    compat: {
      kind: 'gpu',
      lengthMm: 320,
      slots: 3,
      tgpW: 304,
      recommendedPsuW: 750,
      power: '2× PCIe 8 pin',
      bus: 'PCIe 5.0 ×16',
      vramGb: 16,
      vramType: 'GDDR6',
      busWidthBit: 256,
    },
    render: { shape: 'gpu', accent: GRAPHITE, seed: 58, fans: 3, variant: 2 },
  },
  {
    slug: 'geforce-rtx-4060-8gb',
    ref: 'SI-VGA-0140',
    name: 'GeForce RTX 4060 8 GB',
    brand: 'NVIDIA',
    model: 'RTX 4060',
    category: 'tarjetas-graficas',
    priceUsd: 319,
    units: 11,
    blurb: L(
      '115 W de consumo y fuente recomendada de 550 W: se puede meter en un equipo de oficina sin cambiar la fuente. El escalón de entrada honesto para 1080p.',
      '115 W de consumo e fonte recomendada de 550 W: dá para colocar num equipamento de escritório sem trocar a fonte. O degrau de entrada honesto para 1080p.',
    ),
    specs: [
      { label: S.memory, value: '8 GB GDDR6' },
      { label: S.busWidth, value: '128 bit' },
      { label: L('Núcleos CUDA', 'Núcleos CUDA'), value: '3.072' },
      { label: S.bus, value: 'PCIe 4.0 ×8' },
      { label: S.tgp, value: '115 W' },
      { label: S.psu, value: '550 W' },
      { label: S.power, value: '1× PCIe 8 pines' },
      { label: S.length, value: '200 mm' },
      { label: S.slots, value: '2' },
    ],
    compat: {
      kind: 'gpu',
      lengthMm: 200,
      slots: 2,
      tgpW: 115,
      recommendedPsuW: 550,
      power: '1× PCIe 8 pin',
      bus: 'PCIe 4.0 ×8',
      vramGb: 8,
      vramType: 'GDDR6',
      busWidthBit: 128,
    },
    render: { shape: 'gpu', accent: STEEL, seed: 67, fans: 2, variant: 2 },
  },
  {
    slug: 'arc-b580-12gb',
    ref: 'SI-VGA-0147',
    name: 'Arc B580 12 GB',
    brand: 'Intel',
    model: 'Arc B580',
    category: 'tarjetas-graficas',
    priceUsd: 279,
    units: 6,
    arrivedRecently: true,
    blurb: L(
      '12 GB de GDDR6 en 192 bits por debajo de los 300 dólares: más memoria de la que suele traer su rango de precio. Consume 190 W y pide 600 W de fuente.',
      '12 GB de GDDR6 em 192 bits por menos de 300 dólares: mais memória do que a faixa costuma trazer. Consome 190 W e pede fonte de 600 W.',
    ),
    specs: [
      { label: S.memory, value: '12 GB GDDR6' },
      { label: S.busWidth, value: '192 bit' },
      { label: L('Núcleos Xe', 'Núcleos Xe'), value: '20' },
      { label: S.bus, value: 'PCIe 4.0 ×8' },
      { label: S.tgp, value: '190 W' },
      { label: S.psu, value: '600 W' },
      { label: S.power, value: '1× PCIe 8 pines' },
      { label: S.length, value: '272 mm' },
      { label: S.slots, value: '2' },
    ],
    compat: {
      kind: 'gpu',
      lengthMm: 272,
      slots: 2,
      tgpW: 190,
      recommendedPsuW: 600,
      power: '1× PCIe 8 pin',
      bus: 'PCIe 4.0 ×8',
      vramGb: 12,
      vramType: 'GDDR6',
      busWidthBit: 192,
    },
    render: { shape: 'gpu', accent: SKY, seed: 73, fans: 2, variant: 2 },
  },

  // ──────────────────────────────────────────────────────────── procesadores
  {
    slug: 'ryzen-7-9800x3d',
    ref: 'SI-CPU-0203',
    name: 'Ryzen 7 9800X3D',
    brand: 'AMD',
    model: '9800X3D',
    category: 'procesadores',
    priceUsd: 485,
    units: 3,
    featured: true,
    blurb: L(
      'Ocho núcleos con caché apilada bajo el zócalo AM5. Es el procesador que compra quien juega a 1440p y no quiere que el procesador sea el que frene la placa de video.',
      'Oito núcleos com cache empilhado no soquete AM5. É o processador de quem joga em 1440p e não quer que o processador segure a placa de vídeo.',
    ),
    specs: [
      { label: S.socket, value: 'AM5' },
      { label: S.cores, value: '8 / 16' },
      { label: S.tdp, value: '120 W' },
      { label: S.igpu, value: L('Sí', 'Sim') },
      { label: S.ramGen, value: 'DDR5' },
    ],
    compat: { kind: 'cpu', socket: 'AM5', tdpW: 120, cores: 8, threads: 16, igpu: true },
    render: { shape: 'cpu', accent: NICKEL, seed: 21, variant: 0 },
  },
  {
    slug: 'ryzen-7-7800x3d',
    ref: 'SI-CPU-0209',
    name: 'Ryzen 7 7800X3D',
    brand: 'AMD',
    model: '7800X3D',
    category: 'procesadores',
    priceUsd: 384,
    units: 5,
    blurb: L(
      'La generación anterior de la misma idea, en el mismo zócalo AM5. Sigue siendo la compra racional si la placa madre ya está elegida y el presupuesto se va a la placa de video.',
      'A geração anterior da mesma ideia, no mesmo soquete AM5. Continua sendo a compra racional se a placa-mãe já está escolhida e o orçamento vai para a placa de vídeo.',
    ),
    specs: [
      { label: S.socket, value: 'AM5' },
      { label: S.cores, value: '8 / 16' },
      { label: S.tdp, value: '120 W' },
      { label: S.igpu, value: L('Sí', 'Sim') },
      { label: S.ramGen, value: 'DDR5' },
    ],
    compat: { kind: 'cpu', socket: 'AM5', tdpW: 120, cores: 8, threads: 16, igpu: true },
    render: { shape: 'cpu', accent: NICKEL, seed: 27, variant: 0 },
  },
  {
    slug: 'ryzen-5-9600x',
    ref: 'SI-CPU-0214',
    name: 'Ryzen 5 9600X',
    brand: 'AMD',
    model: '9600X',
    category: 'procesadores',
    priceUsd: 195,
    units: 9,
    blurb: L(
      'Seis núcleos a 65 W en AM5. Sobra para jugar a 1080p y para trabajar, y deja margen de presupuesto donde de verdad se nota: memoria y almacenamiento.',
      'Seis núcleos a 65 W em AM5. Sobra para jogar em 1080p e para trabalhar, e deixa margem de orçamento onde realmente aparece: memória e armazenamento.',
    ),
    specs: [
      { label: S.socket, value: 'AM5' },
      { label: S.cores, value: '6 / 12' },
      { label: S.tdp, value: '65 W' },
      { label: S.igpu, value: L('Sí', 'Sim') },
      { label: S.ramGen, value: 'DDR5' },
    ],
    compat: { kind: 'cpu', socket: 'AM5', tdpW: 65, cores: 6, threads: 12, igpu: true },
    render: { shape: 'cpu', accent: NICKEL, seed: 35, variant: 0 },
  },
  {
    slug: 'core-ultra-7-265k',
    ref: 'SI-CPU-0221',
    name: 'Core Ultra 7 265K',
    brand: 'Intel',
    model: 'Ultra 7 265K',
    category: 'procesadores',
    priceUsd: 379,
    units: 4,
    arrivedRecently: true,
    blurb: L(
      'Veinte núcleos repartidos entre rendimiento y eficiencia, sobre el zócalo LGA1851. La opción de quien exporta video o compila más de lo que juega.',
      'Vinte núcleos divididos entre desempenho e eficiência, no soquete LGA1851. A opção de quem exporta vídeo ou compila mais do que joga.',
    ),
    specs: [
      { label: S.socket, value: 'LGA1851' },
      { label: S.cores, value: '20 / 20' },
      { label: S.tdp, value: '125 W' },
      { label: S.igpu, value: L('Sí', 'Sim') },
      { label: S.ramGen, value: 'DDR5' },
    ],
    compat: { kind: 'cpu', socket: 'LGA1851', tdpW: 125, cores: 20, threads: 20, igpu: true },
    render: { shape: 'cpu', accent: STEEL, seed: 41, variant: 1 },
  },
  {
    slug: 'core-i5-14600k',
    ref: 'SI-CPU-0228',
    name: 'Core i5-14600K',
    brand: 'Intel',
    model: 'i5-14600K',
    category: 'procesadores',
    priceUsd: 285,
    units: 8,
    blurb: L(
      'Catorce núcleos en LGA1700, el zócalo con más placas baratas disponibles. Es la vía más económica para llegar a un equipo capaz sin estrenar plataforma.',
      'Catorze núcleos em LGA1700, o soquete com mais placas baratas disponíveis. É o caminho mais econômico para um equipamento capaz sem estrear plataforma.',
    ),
    specs: [
      { label: S.socket, value: 'LGA1700' },
      { label: S.cores, value: '14 / 20' },
      { label: S.tdp, value: '125 W' },
      { label: S.igpu, value: L('Sí', 'Sim') },
      { label: S.ramGen, value: L('DDR4 o DDR5 según la placa', 'DDR4 ou DDR5 conforme a placa') },
    ],
    compat: { kind: 'cpu', socket: 'LGA1700', tdpW: 125, cores: 14, threads: 20, igpu: true },
    render: { shape: 'cpu', accent: STEEL, seed: 49, variant: 1 },
  },

  // ─────────────────────────────────────────────────────────── placas madre
  {
    slug: 'msi-mag-b850-tomahawk-wifi',
    ref: 'SI-MBD-0302',
    name: 'MAG B850 TOMAHAWK WIFI',
    brand: 'MSI',
    model: 'MAG B850 TOMAHAWK WIFI',
    category: 'placas-madre',
    priceUsd: 229,
    units: 4,
    featured: true,
    blurb: L(
      'ATX sobre chipset B850 para AM5, con cuatro ranuras DDR5 y disipadores de VRM que no son decorativos. La base sensata para un Ryzen de ocho núcleos.',
      'ATX com chipset B850 para AM5, quatro slots DDR5 e dissipadores de VRM que não são decorativos. A base sensata para um Ryzen de oito núcleos.',
    ),
    specs: [
      { label: S.socket, value: 'AM5' },
      { label: S.chipset, value: 'B850' },
      { label: S.format, value: 'ATX' },
      { label: S.ramGen, value: 'DDR5' },
      { label: S.ramSlots, value: '4' },
    ],
    compat: {
      kind: 'motherboard',
      socket: 'AM5',
      memory: 'DDR5',
      formFactor: 'ATX',
      memorySlots: 4,
      chipset: 'B850',
    },
    render: { shape: 'motherboard', accent: GRAPHITE, seed: 13, variant: 0 },
  },
  {
    slug: 'asus-tuf-gaming-b650-plus-wifi',
    ref: 'SI-MBD-0308',
    name: 'TUF GAMING B650-PLUS WIFI',
    brand: 'ASUS',
    model: 'TUF GAMING B650-PLUS WIFI',
    category: 'placas-madre',
    priceUsd: 189,
    units: 6,
    blurb: L(
      'ATX para AM5 con B650 y cuatro ranuras DDR5. El escalón donde se deja de pagar por el chipset y se empieza a pagar por la alimentación del procesador.',
      'ATX para AM5 com B650 e quatro slots DDR5. O degrau em que se para de pagar pelo chipset e se começa a pagar pela alimentação do processador.',
    ),
    specs: [
      { label: S.socket, value: 'AM5' },
      { label: S.chipset, value: 'B650' },
      { label: S.format, value: 'ATX' },
      { label: S.ramGen, value: 'DDR5' },
      { label: S.ramSlots, value: '4' },
    ],
    compat: {
      kind: 'motherboard',
      socket: 'AM5',
      memory: 'DDR5',
      formFactor: 'ATX',
      memorySlots: 4,
      chipset: 'B650',
    },
    render: { shape: 'motherboard', accent: GRAPHITE, seed: 19, variant: 1 },
  },
  {
    slug: 'msi-pro-b650m-a-wifi',
    ref: 'SI-MBD-0315',
    name: 'PRO B650M-A WIFI',
    brand: 'MSI',
    model: 'PRO B650M-A WIFI',
    category: 'placas-madre',
    priceUsd: 149,
    units: 7,
    blurb: L(
      'La misma plataforma AM5 en formato Micro-ATX. Si el gabinete es chico, esta placa es la que decide que el armado entre.',
      'A mesma plataforma AM5 em formato Micro-ATX. Se o gabinete é pequeno, é esta placa que decide se a montagem cabe.',
    ),
    specs: [
      { label: S.socket, value: 'AM5' },
      { label: S.chipset, value: 'B650' },
      { label: S.format, value: 'Micro-ATX' },
      { label: S.ramGen, value: 'DDR5' },
      { label: S.ramSlots, value: '4' },
    ],
    compat: {
      kind: 'motherboard',
      socket: 'AM5',
      memory: 'DDR5',
      formFactor: 'Micro-ATX',
      memorySlots: 4,
      chipset: 'B650',
    },
    render: { shape: 'motherboard', accent: STEEL, seed: 24, variant: 2 },
  },
  {
    slug: 'asrock-z890-pro-rs',
    ref: 'SI-MBD-0322',
    name: 'Z890 Pro RS',
    brand: 'ASRock',
    model: 'Z890 Pro RS',
    category: 'placas-madre',
    priceUsd: 209,
    units: 3,
    blurb: L(
      'ATX con chipset Z890 para el zócalo LGA1851. Es la placa que pide un Core Ultra si se quiere ajustar la memoria por encima del perfil de fábrica.',
      'ATX com chipset Z890 para o soquete LGA1851. É a placa que um Core Ultra pede quando se quer ajustar a memória acima do perfil de fábrica.',
    ),
    specs: [
      { label: S.socket, value: 'LGA1851' },
      { label: S.chipset, value: 'Z890' },
      { label: S.format, value: 'ATX' },
      { label: S.ramGen, value: 'DDR5' },
      { label: S.ramSlots, value: '4' },
    ],
    compat: {
      kind: 'motherboard',
      socket: 'LGA1851',
      memory: 'DDR5',
      formFactor: 'ATX',
      memorySlots: 4,
      chipset: 'Z890',
    },
    render: { shape: 'motherboard', accent: GRAPHITE, seed: 29, variant: 0 },
  },
  {
    slug: 'gigabyte-b760m-ds3h',
    ref: 'SI-MBD-0329',
    name: 'B760M DS3H',
    brand: 'Gigabyte',
    model: 'B760M DS3H',
    category: 'placas-madre',
    priceUsd: 119,
    units: 10,
    blurb: L(
      'Micro-ATX para LGA1700 con cuatro ranuras DDR5. La placa que aparece en casi todo armado de presupuesto contenido sobre plataforma Intel.',
      'Micro-ATX para LGA1700 com quatro slots DDR5. A placa que aparece em quase toda montagem de orçamento contido em plataforma Intel.',
    ),
    specs: [
      { label: S.socket, value: 'LGA1700' },
      { label: S.chipset, value: 'B760' },
      { label: S.format, value: 'Micro-ATX' },
      { label: S.ramGen, value: 'DDR5' },
      { label: S.ramSlots, value: '4' },
    ],
    compat: {
      kind: 'motherboard',
      socket: 'LGA1700',
      memory: 'DDR5',
      formFactor: 'Micro-ATX',
      memorySlots: 4,
      chipset: 'B760',
    },
    render: { shape: 'motherboard', accent: STEEL, seed: 34, variant: 2 },
  },

  // ────────────────────────────────────────────────────────── memorias RAM
  {
    slug: 'corsair-vengeance-ddr5-32gb-6000',
    ref: 'SI-RAM-0404',
    name: 'Vengeance DDR5 32 GB (2×16) 6000',
    brand: 'Corsair',
    model: 'Vengeance DDR5 6000 CL30',
    category: 'memorias-ram',
    priceUsd: 500,
    units: 12,
    featured: true,
    blurb: L(
      'El kit que casi siempre es la respuesta correcta: 32 GB en dos módulos, 6000 MT/s y latencia 30. Perfil EXPO/XMP de un clic en la BIOS.',
      'O kit que quase sempre é a resposta certa: 32 GB em dois módulos, 6000 MT/s e latência 30. Perfil EXPO/XMP de um clique na BIOS.',
    ),
    specs: [
      { label: S.ramGen, value: 'DDR5' },
      { label: S.kit, value: '2 × 16 GB' },
      { label: S.speed, value: '6000 MT/s' },
      { label: S.latency, value: 'CL30' },
    ],
    compat: { kind: 'ram', memory: 'DDR5', capacityGb: 32, modules: 2, speedMts: 6000, latency: 'CL30' },
    render: { shape: 'ram', accent: GRAPHITE, seed: 11, variant: 0 },
  },
  {
    slug: 'gskill-trident-z5-neo-32gb-6000',
    ref: 'SI-RAM-0411',
    name: 'Trident Z5 Neo 32 GB (2×16) 6000',
    brand: 'G.Skill',
    model: 'Trident Z5 Neo 6000 CL30',
    category: 'memorias-ram',
    priceUsd: 129,
    units: 5,
    blurb: L(
      'Mismo objetivo que el kit anterior, binado y perfilado para plataformas AMD. Disipador de aluminio sin luces: 44 mm de alto, entra bajo un disipador grande.',
      'Mesmo objetivo do kit anterior, binado e perfilado para plataformas AMD. Dissipador de alumínio sem luzes: 44 mm de altura, cabe sob um cooler grande.',
    ),
    specs: [
      { label: S.ramGen, value: 'DDR5' },
      { label: S.kit, value: '2 × 16 GB' },
      { label: S.speed, value: '6000 MT/s' },
      { label: S.latency, value: 'CL30' },
    ],
    compat: { kind: 'ram', memory: 'DDR5', capacityGb: 32, modules: 2, speedMts: 6000, latency: 'CL30' },
    render: { shape: 'ram', accent: NICKEL, seed: 17, variant: 1 },
  },
  {
    slug: 'kingston-fury-beast-ddr5-16gb-5600',
    ref: 'SI-RAM-0418',
    name: 'FURY Beast DDR5 16 GB (2×8) 5600',
    brand: 'Kingston',
    model: 'FURY Beast DDR5 5600 CL36',
    category: 'memorias-ram',
    priceUsd: 270,
    units: 14,
    blurb: L(
      '16 GB en dos módulos para un armado de entrada en DDR5. Deja las otras dos ranuras libres para duplicar más adelante sin tirar nada.',
      '16 GB em dois módulos para uma montagem de entrada em DDR5. Deixa os outros dois slots livres para dobrar depois sem jogar nada fora.',
    ),
    specs: [
      { label: S.ramGen, value: 'DDR5' },
      { label: S.kit, value: '2 × 8 GB' },
      { label: S.speed, value: '5600 MT/s' },
      { label: S.latency, value: 'CL36' },
    ],
    compat: { kind: 'ram', memory: 'DDR5', capacityGb: 16, modules: 2, speedMts: 5600, latency: 'CL36' },
    render: { shape: 'ram', accent: STEEL, seed: 23, variant: 0 },
  },
  {
    slug: 'corsair-vengeance-lpx-ddr4-16gb-3200',
    ref: 'SI-RAM-0425',
    name: 'Vengeance LPX DDR4 16 GB (2×8) 3200',
    brand: 'Corsair',
    model: 'Vengeance LPX DDR4 3200 CL16',
    category: 'memorias-ram',
    priceUsd: 44,
    units: 9,
    blurb: L(
      'DDR4 para equipos que no van a cambiar de plataforma. Perfil bajo: entra debajo de cualquier disipador de aire sin discutir.',
      'DDR4 para equipamentos que não vão trocar de plataforma. Perfil baixo: cabe sob qualquer cooler a ar sem discussão.',
    ),
    specs: [
      { label: S.ramGen, value: 'DDR4' },
      { label: S.kit, value: '2 × 8 GB' },
      { label: S.speed, value: '3200 MT/s' },
      { label: S.latency, value: 'CL16' },
    ],
    compat: { kind: 'ram', memory: 'DDR4', capacityGb: 16, modules: 2, speedMts: 3200, latency: 'CL16' },
    render: { shape: 'ram', accent: STEEL, seed: 28, variant: 2 },
  },

  // ───────────────────────────────────────────────────────── almacenamiento
  {
    slug: 'samsung-990-pro-2tb',
    ref: 'SI-SSD-0503',
    name: '990 PRO 2 TB',
    brand: 'Samsung',
    model: '990 PRO NVMe',
    category: 'almacenamiento',
    priceUsd: 464,
    listPriceUsd: 519,
    units: 6,
    featured: true,
    blurb: L(
      '7.450 MB/s de lectura sobre PCIe 4.0 en formato M.2 2280. Es el disco que se nota al abrir proyectos grandes, no al copiar archivos sueltos.',
      '7.450 MB/s de leitura em PCIe 4.0 no formato M.2 2280. É o disco que se nota ao abrir projetos grandes, não ao copiar arquivos soltos.',
    ),
    specs: [
      { label: S.format, value: 'M.2 2280' },
      { label: S.bus, value: 'PCIe 4.0 ×4 NVMe' },
      { label: S.capacity, value: '2 TB' },
      { label: S.read, value: '7.450 MB/s' },
      { label: S.write, value: '6.900 MB/s' },
    ],
    compat: {
      kind: 'storage',
      format: 'M.2 2280',
      bus: 'PCIe 4.0 ×4 NVMe',
      capacityGb: 2000,
      readMBs: 7450,
      writeMBs: 6900,
    },
    render: { shape: 'ssd-m2', accent: GRAPHITE, seed: 15, variant: 0 },
  },
  {
    slug: 'wd-black-sn850x-1tb',
    ref: 'SI-SSD-0510',
    name: 'WD_BLACK SN850X 1 TB',
    brand: 'Western Digital',
    model: 'SN850X NVMe',
    category: 'almacenamiento',
    priceUsd: 320,
    units: 8,
    blurb: L(
      '7.300 MB/s en el mismo formato M.2 2280. La diferencia con el escalón de arriba se mide con software, no con el reloj.',
      '7.300 MB/s no mesmo formato M.2 2280. A diferença para o degrau acima se mede com software, não com o relógio.',
    ),
    specs: [
      { label: S.format, value: 'M.2 2280' },
      { label: S.bus, value: 'PCIe 4.0 ×4 NVMe' },
      { label: S.capacity, value: '1 TB' },
      { label: S.read, value: '7.300 MB/s' },
      { label: S.write, value: '6.300 MB/s' },
    ],
    compat: {
      kind: 'storage',
      format: 'M.2 2280',
      bus: 'PCIe 4.0 ×4 NVMe',
      capacityGb: 1000,
      readMBs: 7300,
      writeMBs: 6300,
    },
    render: { shape: 'ssd-m2', accent: GRAPHITE, seed: 22, variant: 1 },
  },
  {
    slug: 'crucial-p3-plus-1tb',
    ref: 'SI-SSD-0517',
    name: 'P3 Plus 1 TB',
    brand: 'Crucial',
    model: 'P3 Plus NVMe',
    category: 'almacenamiento',
    priceUsd: 62,
    units: 15,
    blurb: L(
      'El disco de sistema barato que sigue siendo NVMe: 5.000 MB/s de lectura. Para juegos y sistema operativo la diferencia contra un tope de gama no se ve.',
      'O disco de sistema barato que continua sendo NVMe: 5.000 MB/s de leitura. Para jogos e sistema operacional a diferença para um topo de linha não aparece.',
    ),
    specs: [
      { label: S.format, value: 'M.2 2280' },
      { label: S.bus, value: 'PCIe 4.0 ×4 NVMe' },
      { label: S.capacity, value: '1 TB' },
      { label: S.read, value: '5.000 MB/s' },
      { label: S.write, value: '3.600 MB/s' },
    ],
    compat: {
      kind: 'storage',
      format: 'M.2 2280',
      bus: 'PCIe 4.0 ×4 NVMe',
      capacityGb: 1000,
      readMBs: 5000,
      writeMBs: 3600,
    },
    render: { shape: 'ssd-m2', accent: STEEL, seed: 30, variant: 1 },
  },
  {
    slug: 'samsung-870-evo-1tb',
    ref: 'SI-SSD-0524',
    name: '870 EVO 1 TB',
    brand: 'Samsung',
    model: '870 EVO SATA',
    category: 'almacenamiento',
    priceUsd: 79,
    units: 7,
    blurb: L(
      'SATA de 2,5 pulgadas: más lento que cualquier NVMe, pero entra en equipos que no tienen ranura M.2 libre. Necesita bahía y dos cables.',
      'SATA de 2,5 polegadas: mais lento que qualquer NVMe, mas entra em equipamentos sem slot M.2 livre. Precisa de baia e dois cabos.',
    ),
    specs: [
      { label: S.format, value: '2,5" SATA' },
      { label: S.bus, value: 'SATA 6 Gb/s' },
      { label: S.capacity, value: '1 TB' },
      { label: S.read, value: '560 MB/s' },
      { label: S.write, value: '530 MB/s' },
    ],
    compat: {
      kind: 'storage',
      format: '2.5"',
      bus: 'SATA 6 Gb/s',
      capacityGb: 1000,
      readMBs: 560,
      writeMBs: 530,
    },
    render: { shape: 'ssd-sata', accent: GRAPHITE, seed: 37 },
  },

  // ────────────────────────────────────────────────────────────────── fuentes
  {
    slug: 'corsair-rm750e',
    ref: 'SI-PSU-0602',
    name: 'RM750e 750 W',
    brand: 'Corsair',
    model: 'RM750e',
    category: 'fuentes',
    priceUsd: 85,
    units: 8,
    featured: true,
    blurb: L(
      '750 W con certificación 80 PLUS Gold y cableado totalmente modular. Es el escalón que pide una placa de video de 300 W sin quedarse al límite.',
      '750 W com certificação 80 PLUS Gold e cabeamento totalmente modular. É o degrau que uma placa de vídeo de 300 W pede sem ficar no limite.',
    ),
    specs: [
      { label: S.watts, value: '750 W' },
      { label: S.efficiency, value: '80 PLUS Gold' },
      { label: S.modular, value: L('Totalmente modular', 'Totalmente modular') },
      { label: S.format, value: 'ATX' },
    ],
    compat: { kind: 'psu', wattsW: 750, efficiency: '80 PLUS Gold', modular: 'Full modular', formFactor: 'ATX' },
    render: { shape: 'psu', accent: GRAPHITE, seed: 14, variant: 0 },
  },
  {
    slug: 'seasonic-focus-gx-850',
    ref: 'SI-PSU-0609',
    name: 'FOCUS GX-850 850 W',
    brand: 'Seasonic',
    model: 'FOCUS GX-850',
    category: 'fuentes',
    priceUsd: 139,
    units: 4,
    blurb: L(
      '850 W Gold modulares. El escalón necesario si la placa de video declara 360 W o si el armado va a crecer.',
      '850 W Gold modulares. O degrau necessário se a placa de vídeo declara 360 W ou se a montagem vai crescer.',
    ),
    specs: [
      { label: S.watts, value: '850 W' },
      { label: S.efficiency, value: '80 PLUS Gold' },
      { label: S.modular, value: L('Totalmente modular', 'Totalmente modular') },
      { label: S.format, value: 'ATX' },
    ],
    compat: { kind: 'psu', wattsW: 850, efficiency: '80 PLUS Gold', modular: 'Full modular', formFactor: 'ATX' },
    render: { shape: 'psu', accent: STEEL, seed: 20, variant: 0 },
  },
  {
    slug: 'corsair-rm1000x',
    ref: 'SI-PSU-0616',
    name: 'RM1000x 1000 W',
    brand: 'Corsair',
    model: 'RM1000x',
    category: 'fuentes',
    priceUsd: 189,
    units: 2,
    blurb: L(
      '1000 W Gold modulares, con margen para una placa de video de tope de gama y un procesador de veinte núcleos al mismo tiempo.',
      '1000 W Gold modulares, com margem para uma placa de vídeo topo de linha e um processador de vinte núcleos ao mesmo tempo.',
    ),
    specs: [
      { label: S.watts, value: '1000 W' },
      { label: S.efficiency, value: '80 PLUS Gold' },
      { label: S.modular, value: L('Totalmente modular', 'Totalmente modular') },
      { label: S.format, value: 'ATX' },
    ],
    compat: { kind: 'psu', wattsW: 1000, efficiency: '80 PLUS Gold', modular: 'Full modular', formFactor: 'ATX' },
    render: { shape: 'psu', accent: GRAPHITE, seed: 26, variant: 0 },
  },
  {
    slug: 'msi-mag-a650bn',
    ref: 'SI-PSU-0623',
    name: 'MAG A650BN 650 W',
    brand: 'MSI',
    model: 'MAG A650BN',
    category: 'fuentes',
    priceUsd: 59,
    units: 11,
    blurb: L(
      '650 W Bronze de cableado fijo. Cumple para un armado de entrada; el cable que no se usa hay que esconderlo detrás de la bandeja.',
      '650 W Bronze com cabeamento fixo. Cumpre numa montagem de entrada; o cabo que não se usa precisa ficar escondido atrás da bandeja.',
    ),
    specs: [
      { label: S.watts, value: '650 W' },
      { label: S.efficiency, value: '80 PLUS Bronze' },
      { label: S.modular, value: L('Cableado fijo', 'Cabeamento fixo') },
      { label: S.format, value: 'ATX' },
    ],
    compat: { kind: 'psu', wattsW: 650, efficiency: '80 PLUS Bronze', modular: 'No modular', formFactor: 'ATX' },
    render: { shape: 'psu', accent: STEEL, seed: 33, variant: 1 },
  },

  // ──────────────────────────────────────────────────────────── refrigeración
  {
    slug: 'noctua-nh-d15',
    ref: 'SI-COO-0704',
    name: 'NH-D15',
    brand: 'Noctua',
    model: 'NH-D15',
    category: 'refrigeracion',
    priceUsd: 119,
    units: 3,
    featured: true,
    blurb: L(
      'Doble torre de 165 mm con seis caños de calor. Enfría como una refrigeración líquida de 240 mm y no tiene una bomba que se pueda romper. Medí el gabinete antes.',
      'Torre dupla de 165 mm com seis heat pipes. Refrigera como um water cooler de 240 mm e não tem bomba para quebrar. Meça o gabinete antes.',
    ),
    specs: [
      { label: S.coolType, value: L('Aire, doble torre', 'Ar, torre dupla') },
      { label: S.height, value: '165 mm' },
      { label: S.sockets, value: 'AM5 · AM4 · LGA1700' },
    ],
    compat: { kind: 'cooling', type: 'aire', heightMm: 165, sockets: ['AM5', 'AM4', 'LGA1700'] },
    render: { shape: 'air-cooler', accent: COPPER, seed: 16, variant: 0 },
  },
  {
    slug: 'thermalright-peerless-assassin-120-se',
    ref: 'SI-COO-0711',
    name: 'Peerless Assassin 120 SE',
    brand: 'Thermalright',
    model: 'PA120 SE',
    category: 'refrigeracion',
    priceUsd: 39,
    units: 13,
    blurb: L(
      'Doble torre de 155 mm por menos de cuarenta dólares. Es la pieza que más rendimiento por dólar aporta en todo el catálogo.',
      'Torre dupla de 155 mm por menos de quarenta dólares. É a peça com maior desempenho por dólar de todo o catálogo.',
    ),
    specs: [
      { label: S.coolType, value: L('Aire, doble torre', 'Ar, torre dupla') },
      { label: S.height, value: '155 mm' },
      { label: S.sockets, value: 'AM5 · AM4 · LGA1700' },
    ],
    compat: { kind: 'cooling', type: 'aire', heightMm: 155, sockets: ['AM5', 'AM4', 'LGA1700'] },
    render: { shape: 'air-cooler', accent: NICKEL, seed: 25, variant: 0 },
  },
  {
    slug: 'arctic-liquid-freezer-iii-360',
    ref: 'SI-COO-0718',
    name: 'Liquid Freezer III 360',
    brand: 'ARCTIC',
    model: 'Liquid Freezer III 360',
    category: 'refrigeracion',
    priceUsd: 109,
    units: 5,
    arrivedRecently: true,
    blurb: L(
      'Radiador de 360 mm para los procesadores que de verdad disipan 250 W sostenidos. Verificá que el gabinete acepte un radiador de ese largo antes de comprarlo.',
      'Radiador de 360 mm para os processadores que realmente dissipam 250 W contínuos. Confirme que o gabinete aceita esse comprimento antes de comprar.',
    ),
    specs: [
      { label: S.coolType, value: L('Líquida cerrada', 'Water cooler fechado') },
      { label: S.radiator, value: '360 mm' },
      { label: S.sockets, value: 'AM5 · AM4 · LGA1700 · LGA1851' },
    ],
    compat: {
      kind: 'cooling',
      type: 'liquida',
      radiatorMm: 360,
      sockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    },
    render: { shape: 'aio-cooler', accent: STEEL, seed: 32 },
  },

  // ────────────────────────────────────────────────────────────── gabinetes
  {
    slug: 'lian-li-lancool-216',
    ref: 'SI-CAS-0803',
    name: 'LANCOOL 216',
    brand: 'Lian Li',
    model: 'LANCOOL 216',
    category: 'gabinetes',
    priceUsd: 109,
    units: 4,
    featured: true,
    blurb: L(
      'Torre media con frente de malla y dos ventiladores de 160 mm de fábrica. Acepta placas de video de hasta 392 mm: entra cualquier cosa del catálogo.',
      'Torre média com frente em malha e dois ventiladores de 160 mm de fábrica. Aceita placas de vídeo de até 392 mm: cabe qualquer coisa do catálogo.',
    ),
    specs: [
      { label: S.supports, value: 'ATX · Micro-ATX · Mini-ITX' },
      { label: S.maxGpu, value: '392 mm' },
      { label: S.maxCooler, value: '180 mm' },
      { label: S.maxRad, value: '360 mm' },
    ],
    compat: {
      kind: 'case',
      supports: ['ATX', 'Micro-ATX', 'Mini-ITX'],
      maxGpuMm: 392,
      maxCoolerMm: 180,
      maxRadiatorMm: 360,
    },
    render: { shape: 'case', accent: GRAPHITE, seed: 18, variant: 0 },
  },
  {
    slug: 'nzxt-h5-flow',
    ref: 'SI-CAS-0810',
    name: 'H5 Flow',
    brand: 'NZXT',
    model: 'H5 Flow',
    category: 'gabinetes',
    priceUsd: 94,
    units: 6,
    blurb: L(
      'Torre media compacta y limpia por dentro. Admite hasta 365 mm de placa de video y 165 mm de disipador: medí las dos cosas antes de cerrar el armado.',
      'Torre média compacta e limpa por dentro. Aceita até 365 mm de placa de vídeo e 165 mm de cooler: meça os dois antes de fechar a montagem.',
    ),
    specs: [
      { label: S.supports, value: 'ATX · Micro-ATX · Mini-ITX' },
      { label: S.maxGpu, value: '365 mm' },
      { label: S.maxCooler, value: '165 mm' },
      { label: S.maxRad, value: '280 mm' },
    ],
    compat: {
      kind: 'case',
      supports: ['ATX', 'Micro-ATX', 'Mini-ITX'],
      maxGpuMm: 365,
      maxCoolerMm: 165,
      maxRadiatorMm: 280,
    },
    render: { shape: 'case', accent: STEEL, seed: 36, variant: 1 },
  },
  {
    slug: 'cooler-master-masterbox-q300l',
    ref: 'SI-CAS-0817',
    name: 'MasterBox Q300L',
    brand: 'Cooler Master',
    model: 'MasterBox Q300L',
    category: 'gabinetes',
    priceUsd: 49,
    units: 9,
    blurb: L(
      'Cubo Micro-ATX para un armado chico y barato. No acepta placas ATX y el disipador no puede pasar de 159 mm: es el gabinete que impone límites reales.',
      'Cubo Micro-ATX para uma montagem pequena e barata. Não aceita placas ATX e o cooler não pode passar de 159 mm: é o gabinete que impõe limites reais.',
    ),
    specs: [
      { label: S.supports, value: 'Micro-ATX · Mini-ITX' },
      { label: S.maxGpu, value: '360 mm' },
      { label: S.maxCooler, value: '159 mm' },
      { label: S.maxRad, value: '240 mm' },
    ],
    compat: {
      kind: 'case',
      supports: ['Micro-ATX', 'Mini-ITX'],
      maxGpuMm: 360,
      maxCoolerMm: 159,
      maxRadiatorMm: 240,
    },
    render: { shape: 'case', accent: STEEL, seed: 42, variant: 2 },
  },

  {
    slug: 'cooler-master-nr200p',
    ref: 'SI-CAS-0824',
    name: 'MasterBox NR200P',
    brand: 'Cooler Master',
    model: 'MasterBox NR200P',
    category: 'gabinetes',
    priceUsd: 119,
    units: 3,
    blurb: L(
      'Mini-ITX de 18 litros para un equipo potente que ocupa lo que una torre de escritorio no ocupa. A cambio impone límites reales: 330 mm de placa de video y 155 mm de disipador.',
      'Mini-ITX de 18 litros para um equipamento potente que ocupa o que uma torre não ocupa. Em troca impõe limites reais: 330 mm de placa de vídeo e 155 mm de cooler.',
    ),
    specs: [
      { label: S.supports, value: 'Mini-ITX' },
      { label: S.maxGpu, value: '330 mm' },
      { label: S.maxCooler, value: '155 mm' },
      { label: S.maxRad, value: '280 mm' },
    ],
    compat: {
      kind: 'case',
      supports: ['Mini-ITX'],
      maxGpuMm: 330,
      maxCoolerMm: 155,
      maxRadiatorMm: 280,
    },
    render: { shape: 'case', accent: NICKEL, seed: 47, variant: 2 },
  },

  // ───────────────────────────────────────────────────────────── accesorios
  {
    slug: 'thermal-grizzly-kryonaut-1g',
    ref: 'SI-ACC-0902',
    name: 'Kryonaut 1 g',
    brand: 'Thermal Grizzly',
    model: 'Kryonaut',
    category: 'accesorios',
    priceUsd: 12,
    units: 20,
    blurb: L(
      'Un gramo alcanza para cuatro montajes. La pasta que trae de fábrica el disipador funciona; ésta baja un par de grados y no se seca al primer verano.',
      'Um grama dá para quatro montagens. A pasta que vem de fábrica no cooler funciona; esta baixa alguns graus e não seca no primeiro verão.',
    ),
    specs: [
      { label: S.contents, value: '1 g' },
      { label: L('Aplicaciones', 'Aplicações'), value: '≈ 4' },
    ],
    compat: { kind: 'accessory' },
    render: { shape: 'paste', accent: NICKEL, seed: 45 },
  },
  {
    slug: 'arctic-p12-pwm-pst-5-pack',
    ref: 'SI-ACC-0909',
    name: 'P12 PWM PST — pack de 5',
    brand: 'ARCTIC',
    model: 'P12 PWM PST',
    category: 'accesorios',
    priceUsd: 29,
    units: 8,
    blurb: L(
      'Cinco ventiladores de 120 mm de presión estática, encadenables entre sí con un solo cable al conector de la placa. Cambian más la temperatura que cualquier disipador nuevo.',
      'Cinco ventiladores de 120 mm de pressão estática, encadeáveis entre si com um único cabo até o conector da placa. Mudam mais a temperatura do que qualquer cooler novo.',
    ),
    specs: [
      { label: S.size, value: '120 mm' },
      { label: S.contents, value: L('5 unidades', '5 unidades') },
      { label: L('Control', 'Controle'), value: 'PWM · PST' },
    ],
    compat: { kind: 'accessory' },
    render: { shape: 'fan', accent: STEEL, seed: 52 },
  },
]

export const PRODUCT_BY_SLUG: ReadonlyMap<string, Product> = new Map(
  PRODUCTS.map((product) => [product.slug, product]),
)

export const BRANDS: string[] = Array.from(new Set(PRODUCTS.map((p) => p.brand))).sort((a, b) =>
  a.localeCompare(b, 'es'),
)

export const PRICE_BOUNDS = {
  min: Math.min(...PRODUCTS.map((p) => p.priceUsd)),
  max: Math.max(...PRODUCTS.map((p) => p.priceUsd)),
}
